### ISSUE TITLE
hello

### ISSUE THREAD

**Issue by LiJie20190102** [weaksloth/dolphinscheduler-sdk-java#1]
你好，可以加个好友么，我最近也在搞ds，之前下载过你这份代码，正好如果我有新代码的话可以讨论下，

**Comment by weaksloth** [comment]
> 你好，可以加个好友么，我最近也在搞ds，之前下载过你这份代码，正好如果我有新代码的话可以讨论下，

可以啊，加qq吧就

**Comment by LiJie20190102** [comment]
435574632，或者我加你

**Comment by weaksloth** [comment]
> 435574632，或者我加你

我qq发你qq邮箱了，加不了你好友
