### ISSUE TITLE
数据如何存储？

### ISSUE THREAD

**Issue by li848689491** [weaksloth/dolphinscheduler-sdk-java#11]
我本来想启动个服务，通过HTTP来操作dolphinscheduler的，但是发现了作者的这个仓库。现在有个疑问：
1. 数据的存储是 dolphinscheduler 来做的吗？那我能否将数据存储到我的数据库？
2. 我是否仍然需要自己启动与维护 dolphinscheduler？

**Comment by weaksloth** [comment]
> 我本来想启动个服务，通过HTTP来操作dolphinscheduler的，但是发现了作者的这个仓库。现在有个疑问：
> 
>     1. 数据的存储是 dolphinscheduler 来做的吗？那我能否将数据存储到我的数据库？
> 
>     2. 我是否仍然需要自己启动与维护 dolphinscheduler？

你指的“数据的存储”中的数据是哪方面的数据
