### ISSUE TITLE
误触

### ISSUE THREAD

**Issue by li848689491** [weaksloth/dolphinscheduler-sdk-java#12]

**Comment by weaksloth** [comment]
在3.1.4版本里data是为null的，新版本的data含义是什么你需要看一下代码。
dolphinscheduler运行工作流实例接口是不会创建工作流实例的，所以无法返回工作流实例id给你，具体的任务执行原理你可以去官网学习。
如果你想获取本次启动产生的实例id,你可以调用PrcessInstanceOperator#page()方法进行查询

damon ***@***.***> 于2023年12月18日周一 20:03写道：
