### ISSUE TITLE
sdk中关于停止和重启工作流的方式是否是有误的？

### ISSUE THREAD

**Issue by dzh-cmd** [weaksloth/dolphinscheduler-sdk-java#6]

**Comment by dzh-cmd** [comment]
dolphin的接口好像并没有接受 public static final String RE_RUN_EXECUTE_TYPE = "REPEAT_RUNNING"; 这个参数作为停止和重启工作流的form表单参数

**Comment by weaksloth** [comment]
@dzh-cmd 停止工作流实例的接口没有做。停止工作流和重跑工作流差不多，只是executeType不同

我又看了一遍dolphin的api,sdk中重跑工作流是正确的，你可以比对下`org.apache.dolphinscheduler.api.controller.ExecutorController#execute()`
和
`com.github.weaksloth.dolphins.instance.ProcessInstanceOperator#reRun()`
