### ISSUE TITLE
maven仓库中不存在sdk

### ISSUE THREAD

**Issue by FlickerMi** [weaksloth/dolphinscheduler-sdk-java#7]
mvnrepository中没有找到该sdk，请上传一下。
https://mvnrepository.com/search?q=dolphinscheduler-sdk-java

**Comment by weaksloth** [comment]
是的，考虑到非官方性，应该不会发布到中央仓库。要使用还需要自行install或者deploy到nexus私服

**Comment by FlickerMi** [comment]
好的明白了
